#ifndef __LINX_EVENT_PROCESSOR_DEFINE_H__
#define __LINX_EVENT_PROCESSOR_DEFINE_H__ 

#define LINX_EVENT_PROCESSOR_MIN_THREADS    1
#define LINX_EVENT_PROCESSOR_MAX_THREADS    64

#endif /* __LINX_EVENT_PROCESSOR_DEFINE_H__ */
