#ifndef __LINX_KMOD_MSG_H__
#define __LINX_KMOD_MSG_H__

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <stdint.h>
#endif

#define _packed __attribute__((packed))

/* IOCTL操作命令 */
#define SYSMON_IOCTL_MAGIC  'l'
#define SYSMON_IOCTL_DISABLE_DROPPING_MODE      _IO(SYSMON_IOCTL_MAGIC, 0)
#define SYSMON_IOCTL_ENABLE_DROPPING_MODE       _IO(SYSMON_IOCTL_MAGIC, 1)
#define SYSMON_IOCTL_GET_VTID                   _IO(SYSMON_IOCTL_MAGIC, 2)
#define SYSMON_IOCTL_GTE_PID                    _IO(SYSMON_IOCTL_MAGIC, 3)
#define SYSMON_IOCTL_GTE_CURRENT_TID            _IO(SYSMON_IOCTL_MAGIC, 4)
#define SYSMON_IOCTL_GTE_CURRENT_PID            _IO(SYSMON_IOCTL_MAGIC, 5)
#define SYSMON_IOCTL_ENABLE_SYSCALL             _IO(SYSMON_IOCTL_MAGIC, 6)
#define SYSMON_IOCTL_DISABLE_SYSCALL            _IO(SYSMON_IOCTL_MAGIC, 7)
#define SYSMON_IOCTL_ENABLE_TP                  _IO(SYSMON_IOCTL_MAGIC, 8)
#define SYSMON_IOCTL_DISABLE_TP                 _IO(SYSMON_IOCTL_MAGIC, 9)
#define SYSMON_IOCTL_ENABLE_REAL_ARGS           _IO(SYSMON_IOCTL_MAGIC, 10)  // 使能获取真实参数信息
#define SYSMON_IOCTL_DISABLE_REAL_ARGS          _IO(SYSMON_IOCTL_MAGIC, 11)
#define SYSMON_IOCTL_ENABLE_FDS                 _IO(SYSMON_IOCTL_MAGIC, 12)  // 使能获取文件描述符
#define SYSMON_IOCTL_DISABLE_FDS                _IO(SYSMON_IOCTL_MAGIC, 13)


/* used flag*/
#define SC_UF_NONE           (0)
#define SC_UF_USED           (1 << 1)
#define SC_UF_NEVER_DROP     (1 << 2)
#define SC_UF_ALWAYS_DROP    (1 << 3)


/* 数据长度定义 */
#define MAX_CMDLINE_LEN     (256)
#define SIZE_64             (64)

#define PROC_SIZE       SIZE_64
#define PP_PROC_SIZE    SIZE_64
#define FD_NAME_SIZE    SIZE_64
#define FD_NUM          (12)

/* 操作标志定义 */
#ifndef ENABLE
#define ENABLE      1
#define DISABLE     0
#endif

#define SYSCALL_ENTER   0   /* 系统调用进入 */
#define SYSCALL_EXIT    1   /* 系统调用退出 */

/**********************************************************************
 * 输出信息结构
***********************************************************************/

typedef struct komd_net_info
{
    uint32_t saddr;         // 源IP地址
    uint32_t daddr;         // 目的地址
    uint16_t sport;         // 源端口
    uint16_t dport;         // 目的端口
    uint8_t  protocol;      // 协议类型
    uint8_t direction;      // 方向 (0--出站 1=入站)
}komd_net_info_t;

typedef struct komd_thread_info
{
    char fd_name[FD_NUM][FD_NAME_SIZE];           /* 线程文件描述符 */
}komd_thread_info_t;


// 事件头结构
typedef struct event_header
{
    uint64_t ts;            /* 时间戳 */
    uint32_t type;          /* 事件类型 */
    uint32_t syscall_nr;    /* 系统调用号 */
    uint32_t pid;           /* 进程ID */
    uint32_t tid;           /* 线程ID */
    uint32_t user;          /* 操作用户 */
    uint32_t len;           /* 事件总长度  */
    uint32_t ppid;          /* 父进程ID */
    int32_t  res;           /* 返回值 */

    struct komd_net_info net;       /* 网络信息结构 */
    uint8_t net_flag;               /* 网络标记 */
    char proc[PROC_SIZE];           /* 操作命令 */
    char pp_proc[PP_PROC_SIZE];     /* 父进程操作命令 */
    char cmdline[MAX_CMDLINE_LEN];  /* 操作完整命令 */
    int fd_val[FD_NUM];             /* 文件操作描述符 */
    uint8_t args[0];                /* 参数数据 */
}event_header_t;

/**********************************************************************
 * 环形缓冲区信息结构
***********************************************************************/
struct kmod_ringbuffer_info
{
    uint32_t head;          // 生产者位置
    uint32_t tail;          // 消费者者位置
    uint64_t n_evts;        // 收集的事件数量
    uint64_t n_drop_evts;   // 丢弃的事件数量
};


/**********************************************************************
 * 系统调用具体参数信息数据结构
***********************************************************************/
struct event_filler_arguments;

typedef int (*filler_callback_t)(struct event_filler_arguments *args);
/* 实际参数回调数据结构 */
struct sysmon_event_entry {
	filler_callback_t filler_callback;
};

typedef enum {
    SYSMON_GENERIC_E = 0,
	SYSMON_GENERIC_X = 1,
	SYSMON_SYSCALL_OPEN_E = 2,
	SYSMON_SYSCALL_OPEN_X = 3,
    SYSMON_SYSCALL_CLOSE_E = 4,
	SYSMON_SYSCALL_CLOSE_X = 5,
	SYSMON_SYSCALL_READ_E = 6,
	SYSMON_SYSCALL_READ_X = 7,
	SYSMON_SYSCALL_WRITE_E = 8,
	SYSMON_SYSCALL_WRITE_X = 9,
    SYSMON_SYSCALL_BRK_1_E = 10,
	SYSMON_SYSCALL_BRK_1_X = 11,
	SYSMON_SYSCALL_EXECVE_8_E = 12,
	SYSMON_SYSCALL_EXECVE_8_X = 13,
	SYSMON_SYSCALL_CLONE_11_E = 14,
	SYSMON_SYSCALL_CLONE_11_X = 15,
	SYSMON_PROCEXIT_E = 16,
	SYSMON_PROCEXIT_X = 17, /* This should never be called */
	SYSMON_SOCKET_SOCKET_E = 18,
	SYSMON_SOCKET_SOCKET_X = 19,
	SYSMON_SOCKET_BIND_E = 20,
	SYSMON_SOCKET_BIND_X = 21,
	SYSMON_SOCKET_CONNECT_E = 22,
	SYSMON_SOCKET_CONNECT_X = 23,
	SYSMON_SOCKET_LISTEN_E = 24,
	SYSMON_SOCKET_LISTEN_X = 25,
	SYSMON_SOCKET_ACCEPT_E = 26,
	SYSMON_SOCKET_ACCEPT_X = 27,
	SYSMON_SOCKET_SEND_E = 28,
	SYSMON_SOCKET_SEND_X = 29,
	SYSMON_SOCKET_SENDTO_E = 30,
	SYSMON_SOCKET_SENDTO_X = 31,
	SYSMON_SOCKET_RECV_E = 32,
	SYSMON_SOCKET_RECV_X = 33,
	SYSMON_SOCKET_RECVFROM_E = 34,
	SYSMON_SOCKET_RECVFROM_X = 35,
	SYSMON_SOCKET_SHUTDOWN_E = 36,
	SYSMON_SOCKET_SHUTDOWN_X = 37,
	SYSMON_SOCKET_GETSOCKNAME_E = 38,
	SYSMON_SOCKET_GETSOCKNAME_X = 39,
	SYSMON_SOCKET_GETPEERNAME_E = 40,
	SYSMON_SOCKET_GETPEERNAME_X = 41,
	SYSMON_SOCKET_SOCKETPAIR_E = 42,
	SYSMON_SOCKET_SOCKETPAIR_X = 43,
	SYSMON_SOCKET_SETSOCKOPT_E = 44,
	SYSMON_SOCKET_SETSOCKOPT_X = 45,
	SYSMON_SOCKET_GETSOCKOPT_E = 46,
	SYSMON_SOCKET_GETSOCKOPT_X = 47,
	SYSMON_SOCKET_SENDMSG_E = 48,
	SYSMON_SOCKET_SENDMSG_X = 49,
	SYSMON_SOCKET_SENDMMSG_E = 50,
	SYSMON_SOCKET_SENDMMSG_X = 51,
	SYSMON_SOCKET_RECVMSG_E = 52,
	SYSMON_SOCKET_RECVMSG_X = 53,
	SYSMON_SOCKET_RECVMMSG_E = 54,
	SYSMON_SOCKET_RECVMMSG_X = 55,
	SYSMON_SOCKET_ACCEPT4_E = 56,
	SYSMON_SOCKET_ACCEPT4_X = 57,
	SYSMON_SYSCALL_CREAT_E = 58,
	SYSMON_SYSCALL_CREAT_X = 59,
	SYSMON_SYSCALL_PIPE_E = 60,
	SYSMON_SYSCALL_PIPE_X = 61,
	SYSMON_SYSCALL_EVENTFD_E = 62,
	SYSMON_SYSCALL_EVENTFD_X = 63,
	SYSMON_SYSCALL_FUTEX_E = 64,
	SYSMON_SYSCALL_FUTEX_X = 65,
	SYSMON_SYSCALL_STAT_E = 66,
	SYSMON_SYSCALL_STAT_X = 67,
	SYSMON_SYSCALL_LSTAT_E = 68,
	SYSMON_SYSCALL_LSTAT_X = 69,
	SYSMON_SYSCALL_FSTAT_E = 70,
	SYSMON_SYSCALL_FSTAT_X = 71,
	SYSMON_SYSCALL_STAT64_E = 72,
	SYSMON_SYSCALL_STAT64_X = 73,
	SYSMON_SYSCALL_LSTAT64_E = 74,
	SYSMON_SYSCALL_LSTAT64_X = 75,
	SYSMON_SYSCALL_FSTAT64_E = 76,
	SYSMON_SYSCALL_FSTAT64_X = 77,
	SYSMON_SYSCALL_EPOLLWAIT_E = 78,
	SYSMON_SYSCALL_EPOLLWAIT_X = 79,
	SYSMON_SYSCALL_POLL_E = 80,
	SYSMON_SYSCALL_POLL_X = 81,
	SYSMON_SYSCALL_SELECT_E = 82,
	SYSMON_SYSCALL_SELECT_X = 83,
	SYSMON_SYSCALL_NEWSELECT_E = 84,
	SYSMON_SYSCALL_NEWSELECT_X = 85,
	SYSMON_SYSCALL_LSEEK_E = 86,
	SYSMON_SYSCALL_LSEEK_X = 87,
	SYSMON_SYSCALL_LLSEEK_E = 88,
	SYSMON_SYSCALL_LLSEEK_X = 89,
	SYSMON_SYSCALL_IOCTL_2_E = 90,
	SYSMON_SYSCALL_IOCTL_2_X = 91,
	SYSMON_SYSCALL_GETCWD_E = 92,
	SYSMON_SYSCALL_GETCWD_X = 93,
	SYSMON_SYSCALL_CHDIR_E = 94,
	SYSMON_SYSCALL_CHDIR_X = 95,
	SYSMON_SYSCALL_FCHDIR_E = 96,
	SYSMON_SYSCALL_FCHDIR_X = 97,
	/* SYSMONkdir/rmdir events are not emitted anymore */
	SYSMON_SYSCALL_MKDIR_E = 98,
	SYSMON_SYSCALL_MKDIR_X = 99,
	SYSMON_SYSCALL_RMDIR_E = 100,
	SYSMON_SYSCALL_RMDIR_X = 101,
	SYSMON_SYSCALL_OPENAT_E = 102,
	SYSMON_SYSCALL_OPENAT_X = 103,
	SYSMON_SYSCALL_LINK_E = 104,
	SYSMON_SYSCALL_LINK_X = 105,
	SYSMON_SYSCALL_LINKAT_E = 106,
	SYSMON_SYSCALL_LINKAT_X = 107,
	SYSMON_SYSCALL_UNLINK_E = 108,
	SYSMON_SYSCALL_UNLINK_X = 109,
	SYSMON_SYSCALL_UNLINKAT_E = 110,
	SYSMON_SYSCALL_UNLINKAT_X = 111,
	SYSMON_SYSCALL_PREAD_E = 112,
	SYSMON_SYSCALL_PREAD_X = 113,
	SYSMON_SYSCALL_PWRITE_E = 114,
	SYSMON_SYSCALL_PWRITE_X = 115,
	SYSMON_SYSCALL_READV_E = 116,
	SYSMON_SYSCALL_READV_X = 117,
	SYSMON_SYSCALL_WRITEV_E = 118,
	SYSMON_SYSCALL_WRITEV_X = 119,
	SYSMON_SYSCALL_PREADV_E = 120,
	SYSMON_SYSCALL_PREADV_X = 121,
	SYSMON_SYSCALL_PWRITEV_E = 122,
	SYSMON_SYSCALL_PWRITEV_X = 123,
	SYSMON_SYSCALL_DUP_E = 124,
	SYSMON_SYSCALL_DUP_X = 125,
	SYSMON_SYSCALL_SIGNALFD_E = 126,
	SYSMON_SYSCALL_SIGNALFD_X = 127,
	SYSMON_SYSCALL_KILL_E = 128,
	SYSMON_SYSCALL_KILL_X = 129,
	SYSMON_SYSCALL_TKILL_E = 130,
	SYSMON_SYSCALL_TKILL_X = 131,
	SYSMON_SYSCALL_TGKILL_E = 132,
	SYSMON_SYSCALL_TGKILL_X = 133,
	SYSMON_SYSCALL_NANOSLEEP_E = 134,
	SYSMON_SYSCALL_NANOSLEEP_X = 135,
	SYSMON_SYSCALL_TIMERFD_CREATE_E = 136,
	SYSMON_SYSCALL_TIMERFD_CREATE_X = 137,
	SYSMON_SYSCALL_INOTIFY_INIT_E = 138,
	SYSMON_SYSCALL_INOTIFY_INIT_X = 139,
	SYSMON_SYSCALL_GETRLIMIT_E = 140,
	SYSMON_SYSCALL_GETRLIMIT_X = 141,
	SYSMON_SYSCALL_SETRLIMIT_E = 142,
	SYSMON_SYSCALL_SETRLIMIT_X = 143,
	SYSMON_SYSCALL_PRLIMIT_E = 144,
	SYSMON_SYSCALL_PRLIMIT_X = 145,
	SYSMON_SCHEDSWITCH_1_E = 146,
	SYSMON_SCHEDSWITCH_1_X = 147, /* This should never be called */
	SYSMON_DROP_E = 148,          /* For internal use */
	SYSMON_DROP_X = 149,          /* For internal use */
	SYSMON_SYSCALL_FCNTL_E = 150, /* For internal use */
	SYSMON_SYSCALL_FCNTL_X = 151, /* For internal use */
	SYSMON_SCHEDSWITCH_6_E = 152,
	SYSMON_SCHEDSWITCH_6_X = 153, /* This should never be called */
	SYSMON_SYSCALL_EXECVE_13_E = 154,
	SYSMON_SYSCALL_EXECVE_13_X = 155,
	SYSMON_SYSCALL_CLONE_16_E = 156,
	SYSMON_SYSCALL_CLONE_16_X = 157,
	SYSMON_SYSCALL_BRK_4_E = 158,
	SYSMON_SYSCALL_BRK_4_X = 159,
	SYSMON_SYSCALL_MMAP_E = 160,
	SYSMON_SYSCALL_MMAP_X = 161,
	SYSMON_SYSCALL_MMAP2_E = 162,
	SYSMON_SYSCALL_MMAP2_X = 163,
	SYSMON_SYSCALL_MUNMAP_E = 164,
	SYSMON_SYSCALL_MUNMAP_X = 165,
	SYSMON_SYSCALL_SPLICE_E = 166,
	SYSMON_SYSCALL_SPLICE_X = 167,
	SYSMON_SYSCALL_PTRACE_E = 168,
	SYSMON_SYSCALL_PTRACE_X = 169,
	SYSMON_SYSCALL_IOCTL_3_E = 170,
	SYSMON_SYSCALL_IOCTL_3_X = 171,
	SYSMON_SYSCALL_EXECVE_14_E = 172,
	SYSMON_SYSCALL_EXECVE_14_X = 173,
	SYSMON_SYSCALL_RENAME_E = 174,
	SYSMON_SYSCALL_RENAME_X = 175,
	SYSMON_SYSCALL_RENAMEAT_E = 176,
	SYSMON_SYSCALL_RENAMEAT_X = 177,
	SYSMON_SYSCALL_SYMLINK_E = 178,
	SYSMON_SYSCALL_SYMLINK_X = 179,
	SYSMON_SYSCALL_SYMLINKAT_E = 180,
	SYSMON_SYSCALL_SYMLINKAT_X = 181,
	SYSMON_SYSCALL_FORK_E = 182,
	SYSMON_SYSCALL_FORK_X = 183,
	SYSMON_SYSCALL_VFORK_E = 184,
	SYSMON_SYSCALL_VFORK_X = 185,
	SYSMON_PROCEXIT_1_E = 186,
	SYSMON_PROCEXIT_1_X = 187, /* This should never be called */
	SYSMON_SYSCALL_SENDFILE_E = 188,
	SYSMON_SYSCALL_SENDFILE_X = 189, /* This should never be called */
	SYSMON_SYSCALL_QUOTACTL_E = 190,
	SYSMON_SYSCALL_QUOTACTL_X = 191,
	SYSMON_SYSCALL_SETRESUID_E = 192,
	SYSMON_SYSCALL_SETRESUID_X = 193,
	SYSMON_SYSCALL_SETRESGID_E = 194,
	SYSMON_SYSCALL_SETRESGID_X = 195,
	SYSMON_SCAPEVENT_E = 196,
	SYSMON_SCAPEVENT_X = 197, /* This should never be called */
	SYSMON_SYSCALL_SETUID_E = 198,
	SYSMON_SYSCALL_SETUID_X = 199,
	SYSMON_SYSCALL_SETGID_E = 200,
	SYSMON_SYSCALL_SETGID_X = 201,
	SYSMON_SYSCALL_GETUID_E = 202,
	SYSMON_SYSCALL_GETUID_X = 203,
	SYSMON_SYSCALL_GETEUID_E = 204,
	SYSMON_SYSCALL_GETEUID_X = 205,
	SYSMON_SYSCALL_GETGID_E = 206,
	SYSMON_SYSCALL_GETGID_X = 207,
	SYSMON_SYSCALL_GETEGID_E = 208,
	SYSMON_SYSCALL_GETEGID_X = 209,
	SYSMON_SYSCALL_GETRESUID_E = 210,
	SYSMON_SYSCALL_GETRESUID_X = 211,
	SYSMON_SYSCALL_GETRESGID_E = 212,
	SYSMON_SYSCALL_GETRESGID_X = 213,
	SYSMON_SYSCALL_EXECVE_15_E = 214,
	SYSMON_SYSCALL_EXECVE_15_X = 215,
	SYSMON_SYSCALL_CLONE_17_E = 216,
	SYSMON_SYSCALL_CLONE_17_X = 217,
	SYSMON_SYSCALL_FORK_17_E = 218,
	SYSMON_SYSCALL_FORK_17_X = 219,
	SYSMON_SYSCALL_VFORK_17_E = 220,
	SYSMON_SYSCALL_VFORK_17_X = 221,
	SYSMON_SYSCALL_CLONE_20_E = 222,
	SYSMON_SYSCALL_CLONE_20_X = 223,
	SYSMON_SYSCALL_FORK_20_E = 224,
	SYSMON_SYSCALL_FORK_20_X = 225,
	SYSMON_SYSCALL_VFORK_20_E = 226,
	SYSMON_SYSCALL_VFORK_20_X = 227,
	SYSMON_CONTAINER_E = 228,
	SYSMON_CONTAINER_X = 229,
	SYSMON_SYSCALL_EXECVE_16_E = 230,
	SYSMON_SYSCALL_EXECVE_16_X = 231,
	SYSMON_SIGNALDELIVER_E = 232,
	SYSMON_SIGNALDELIVER_X = 233, /* This should never be called */
	SYSMON_PROCINFO_E = 234,
	SYSMON_PROCINFO_X = 235, /* This should never be called */
	SYSMON_SYSCALL_GETDENTS_E = 236,
	SYSMON_SYSCALL_GETDENTS_X = 237,
	SYSMON_SYSCALL_GETDENTS64_E = 238,
	SYSMON_SYSCALL_GETDENTS64_X = 239,
	SYSMON_SYSCALL_SETNS_E = 240,
	SYSMON_SYSCALL_SETNS_X = 241,
	SYSMON_SYSCALL_FLOCK_E = 242,
	SYSMON_SYSCALL_FLOCK_X = 243,
	SYSMON_CPU_HOTPLUG_E = 244,
	SYSMON_CPU_HOTPLUG_X = 245, /* This should never be called */
	SYSMON_SOCKET_ACCEPT_5_E = 246,
	SYSMON_SOCKET_ACCEPT_5_X = 247,
	SYSMON_SOCKET_ACCEPT4_5_E = 248,
	SYSMON_SOCKET_ACCEPT4_5_X = 249,
	SYSMON_SYSCALL_SEMOP_E = 250,
	SYSMON_SYSCALL_SEMOP_X = 251,
	SYSMON_SYSCALL_SEMCTL_E = 252,
	SYSMON_SYSCALL_SEMCTL_X = 253,
	SYSMON_SYSCALL_PPOLL_E = 254,
	SYSMON_SYSCALL_PPOLL_X = 255,
	SYSMON_SYSCALL_MOUNT_E = 256,
	SYSMON_SYSCALL_MOUNT_X = 257,
	SYSMON_SYSCALL_UMOUNT_E = 258,
	SYSMON_SYSCALL_UMOUNT_X = 259,
	SYSMON_K8S_E = 260,
	SYSMON_K8S_X = 261,
	SYSMON_SYSCALL_SEMGET_E = 262,
	SYSMON_SYSCALL_SEMGET_X = 263,
	SYSMON_SYSCALL_ACCESS_E = 264,
	SYSMON_SYSCALL_ACCESS_X = 265,
	SYSMON_SYSCALL_CHROOT_E = 266,
	SYSMON_SYSCALL_CHROOT_X = 267,
	SYSMON_TRACER_E = 268,
	SYSMON_TRACER_X = 269,
	SYSMON_MESOS_E = 270,
	SYSMON_MESOS_X = 271,
	SYSMON_CONTAINER_JSON_E = 272,
	SYSMON_CONTAINER_JSON_X = 273,
	SYSMON_SYSCALL_SETSID_E = 274,
	SYSMON_SYSCALL_SETSID_X = 275,
	SYSMON_SYSCALL_MKDIR_2_E = 276,
	SYSMON_SYSCALL_MKDIR_2_X = 277,
	SYSMON_SYSCALL_RMDIR_2_E = 278,
	SYSMON_SYSCALL_RMDIR_2_X = 279,
	SYSMON_NOTIFICATION_E = 280,
	SYSMON_NOTIFICATION_X = 281,
	SYSMON_SYSCALL_EXECVE_17_E = 282,
	SYSMON_SYSCALL_EXECVE_17_X = 283,
	SYSMON_SYSCALL_UNSHARE_E = 284,
	SYSMON_SYSCALL_UNSHARE_X = 285,
	SYSMON_INFRASTRUCTURE_EVENT_E = 286,
	SYSMON_INFRASTRUCTURE_EVENT_X = 287,
	SYSMON_SYSCALL_EXECVE_18_E = 288,
	SYSMON_SYSCALL_EXECVE_18_X = 289,
	SYSMON_PAGE_FAULT_E = 290,
	SYSMON_PAGE_FAULT_X = 291,
	SYSMON_SYSCALL_EXECVE_19_E = 292,
	SYSMON_SYSCALL_EXECVE_19_X = 293,
	SYSMON_SYSCALL_SETPGID_E = 294,
	SYSMON_SYSCALL_SETPGID_X = 295,
	SYSMON_SYSCALL_BPF_E = 296,
	SYSMON_SYSCALL_BPF_X = 297,
	SYSMON_SYSCALL_SECCOMP_E = 298,
	SYSMON_SYSCALL_SECCOMP_X = 299,
	SYSMON_SYSCALL_UNLINK_2_E = 300,
	SYSMON_SYSCALL_UNLINK_2_X = 301,
	SYSMON_SYSCALL_UNLINKAT_2_E = 302,
	SYSMON_SYSCALL_UNLINKAT_2_X = 303,
	SYSMON_SYSCALL_MKDIRAT_E = 304,
	SYSMON_SYSCALL_MKDIRAT_X = 305,
	SYSMON_SYSCALL_OPENAT_2_E = 306,
	SYSMON_SYSCALL_OPENAT_2_X = 307,
	SYSMON_SYSCALL_LINK_2_E = 308,
	SYSMON_SYSCALL_LINK_2_X = 309,
	SYSMON_SYSCALL_LINKAT_2_E = 310,
	SYSMON_SYSCALL_LINKAT_2_X = 311,
	SYSMON_SYSCALL_FCHMODAT_E = 312,
	SYSMON_SYSCALL_FCHMODAT_X = 313,
	SYSMON_SYSCALL_CHMOD_E = 314,
	SYSMON_SYSCALL_CHMOD_X = 315,
	SYSMON_SYSCALL_FCHMOD_E = 316,
	SYSMON_SYSCALL_FCHMOD_X = 317,
	SYSMON_SYSCALL_RENAMEAT2_E = 318,
	SYSMON_SYSCALL_RENAMEAT2_X = 319,
	SYSMON_SYSCALL_USERFAULTFD_E = 320,
	SYSMON_SYSCALL_USERFAULTFD_X = 321,
	SYSMON_PLUGINEVENT_E = 322,
	SYSMON_PLUGINEVENT_X = 323,
	SYSMON_CONTAINER_JSON_2_E = 324,
	SYSMON_CONTAINER_JSON_2_X = 325,
	SYSMON_SYSCALL_OPENAT2_E = 326,
	SYSMON_SYSCALL_OPENAT2_X = 327,
	SYSMON_SYSCALL_MPROTECT_E = 328,
	SYSMON_SYSCALL_MPROTECT_X = 329,
	SYSMON_SYSCALL_EXECVEAT_E = 330,
	SYSMON_SYSCALL_EXECVEAT_X = 331,
	SYSMON_SYSCALL_COPY_FILE_RANGE_E = 332,
	SYSMON_SYSCALL_COPY_FILE_RANGE_X = 333,
	SYSMON_SYSCALL_CLONE3_E = 334,
	SYSMON_SYSCALL_CLONE3_X = 335,
	SYSMON_SYSCALL_OPEN_BY_HANDLE_AT_E = 336,
	SYSMON_SYSCALL_OPEN_BY_HANDLE_AT_X = 337,
	SYSMON_SYSCALL_IO_URING_SETUP_E = 338,
	SYSMON_SYSCALL_IO_URING_SETUP_X = 339,
	SYSMON_SYSCALL_IO_URING_ENTER_E = 340,
	SYSMON_SYSCALL_IO_URING_ENTER_X = 341,
	SYSMON_SYSCALL_IO_URING_REGISTER_E = 342,
	SYSMON_SYSCALL_IO_URING_REGISTER_X = 343,
	SYSMON_SYSCALL_MLOCK_E = 344,
	SYSMON_SYSCALL_MLOCK_X = 345,
	SYSMON_SYSCALL_MUNLOCK_E = 346,
	SYSMON_SYSCALL_MUNLOCK_X = 347,
	SYSMON_SYSCALL_MLOCKALL_E = 348,
	SYSMON_SYSCALL_MLOCKALL_X = 349,
	SYSMON_SYSCALL_MUNLOCKALL_E = 350,
	SYSMON_SYSCALL_MUNLOCKALL_X = 351,
	SYSMON_SYSCALL_CAPSET_E = 352,
	SYSMON_SYSCALL_CAPSET_X = 353,
	SYSMON_USER_ADDED_E = 354,
	SYSMON_USER_ADDED_X = 355,
	SYSMON_USER_DELETED_E = 356,
	SYSMON_USER_DELETED_X = 357,
	SYSMON_GROUP_ADDED_E = 358,
	SYSMON_GROUP_ADDED_X = 359,
	SYSMON_GROUP_DELETED_E = 360,
	SYSMON_GROUP_DELETED_X = 361,
	SYSMON_SYSCALL_DUP2_E = 362,
	SYSMON_SYSCALL_DUP2_X = 363,
	SYSMON_SYSCALL_DUP3_E = 364,
	SYSMON_SYSCALL_DUP3_X = 365,
	SYSMON_SYSCALL_DUP_1_E = 366,
	SYSMON_SYSCALL_DUP_1_X = 367,
	SYSMON_SYSCALL_BPF_2_E = 368,
	SYSMON_SYSCALL_BPF_2_X = 369,
	SYSMON_SYSCALL_MLOCK2_E = 370,
	SYSMON_SYSCALL_MLOCK2_X = 371,
	SYSMON_SYSCALL_FSCONFIG_E = 372,
	SYSMON_SYSCALL_FSCONFIG_X = 373,
	SYSMON_SYSCALL_EPOLL_CREATE_E = 374,
	SYSMON_SYSCALL_EPOLL_CREATE_X = 375,
	SYSMON_SYSCALL_EPOLL_CREATE1_E = 376,
	SYSMON_SYSCALL_EPOLL_CREATE1_X = 377,
	SYSMON_SYSCALL_CHOWN_E = 378,
	SYSMON_SYSCALL_CHOWN_X = 379,
	SYSMON_SYSCALL_LCHOWN_E = 380,
	SYSMON_SYSCALL_LCHOWN_X = 381,
	SYSMON_SYSCALL_FCHOWN_E = 382,
	SYSMON_SYSCALL_FCHOWN_X = 383,
	SYSMON_SYSCALL_FCHOWNAT_E = 384,
	SYSMON_SYSCALL_FCHOWNAT_X = 385,
	SYSMON_SYSCALL_UMOUNT_1_E = 386,
	SYSMON_SYSCALL_UMOUNT_1_X = 387,
	SYSMON_SOCKET_ACCEPT4_6_E = 388,
	SYSMON_SOCKET_ACCEPT4_6_X = 389,
	SYSMON_SYSCALL_UMOUNT2_E = 390,
	SYSMON_SYSCALL_UMOUNT2_X = 391,
	SYSMON_SYSCALL_PIPE2_E = 392,
	SYSMON_SYSCALL_PIPE2_X = 393,
	SYSMON_SYSCALL_INOTIFY_INIT1_E = 394,
	SYSMON_SYSCALL_INOTIFY_INIT1_X = 395,
	SYSMON_SYSCALL_EVENTFD2_E = 396,
	SYSMON_SYSCALL_EVENTFD2_X = 397,
	SYSMON_SYSCALL_SIGNALFD4_E = 398,
	SYSMON_SYSCALL_SIGNALFD4_X = 399,
	SYSMON_SYSCALL_PRCTL_E = 400,
	SYSMON_SYSCALL_PRCTL_X = 401,
	SYSMON_ASYNCEVENT_E = 402,
	SYSMON_ASYNCEVENT_X = 403,
	SYSMON_SYSCALL_MEMFD_CREATE_E = 404,
	SYSMON_SYSCALL_MEMFD_CREATE_X = 405,
	SYSMON_SYSCALL_PIDFD_GETFD_E = 406,
	SYSMON_SYSCALL_PIDFD_GETFD_X = 407,
	SYSMON_SYSCALL_PIDFD_OPEN_E = 408,
	SYSMON_SYSCALL_PIDFD_OPEN_X = 409,
	SYSMON_SYSCALL_INIT_MODULE_E = 410,
	SYSMON_SYSCALL_INIT_MODULE_X = 411,
	SYSMON_SYSCALL_FINIT_MODULE_E = 412,
	SYSMON_SYSCALL_FINIT_MODULE_X = 413,
	SYSMON_SYSCALL_MKNOD_E = 414,
	SYSMON_SYSCALL_MKNOD_X = 415,
	SYSMON_SYSCALL_MKNODAT_E = 416,
	SYSMON_SYSCALL_MKNODAT_X = 417,
	SYSMON_SYSCALL_NEWFSTATAT_E = 418,
	SYSMON_SYSCALL_NEWFSTATAT_X = 419,
	SYSMON_SYSCALL_PROCESS_VM_READV_E = 420,
	SYSMON_SYSCALL_PROCESS_VM_READV_X = 421,
	SYSMON_SYSCALL_PROCESS_VM_WRITEV_E = 422,
	SYSMON_SYSCALL_PROCESS_VM_WRITEV_X = 423,
	SYSMON_SYSCALL_DELETE_MODULE_E = 424,
	SYSMON_SYSCALL_DELETE_MODULE_X = 425,
	SYSMON_SYSCALL_SETREUID_E = 426,
	SYSMON_SYSCALL_SETREUID_X = 427,
	SYSMON_SYSCALL_SETREGID_E = 428,
	SYSMON_SYSCALL_SETREGID_X = 429,
    SYSMON_SYSCALL_MAX,
} sysmon_event_code;


enum sysmon_param_type {
	PT_NONE = 0,
	PT_INT8 = 1,
	PT_INT16 = 2,
	PT_INT32 = 3,
    PT_INT64 = 4,
	PT_UINT8 = 5,
	PT_UINT16 = 6,
	PT_UINT32 = 7,
	PT_UINT64 = 8,
	PT_CHARBUF = 9, 
};

struct sysmon_param_info {
	char name[32];                  /* 参数名称 */
	enum sysmon_param_type type;    /* 数据类型：如uint32_t、uint16_t */
};

struct syscall_evt_pair {
	int flags;                              /*  操作标志：系统调用启用 |  丢弃模式标志 */
	sysmon_event_code enter_event_type;     /* 系统调用进入 */
	sysmon_event_code exit_event_type;
} _packed;

struct sysmon_event_info
{
    char name[32];
    uint32_t nparams;
    struct sysmon_param_info params[8];
};

typedef enum {
	SYSMON_TP_SYS_ENTER = 0,
	SYSMON_TP_SYS_EXIT = 1,
    SYSMON_TP_SYS_SCHED_SWITCH = 2,
    SYSMON_TP_MAX,
}sysmon_tp_code;

extern const struct syscall_evt_pair g_syscall_table[];
extern const struct sysmon_event_info g_event_info[];

#endif /* __LINX_KMOD_MSG_H__  */