#ifndef __LINX_PROCESS_STATE_H__
#define __LINX_PROCESS_STATE_H__ 

typedef enum {
    LINX_PROCESS_STATE_RUNNING = 0,
    LINX_PROCESS_STATE_SLEEPING,
    LINX_PROCESS_STATE_ZOMBIE,
    LINX_PROCESS_STATE_STOPPED,
    LINX_PROCESS_STATE_EXITED,
    LINX_PROCESS_STATE_UNKNOWN
} linx_process_state_t;

#endif /* __LINX_PROCESS_STATE_H__ */
