#ifndef __LINX_FD_TYPE_H__
#define __LINX_FD_TYPE_H__

typedef enum {
    LINX_FD_TYPE_UNINITIALIZED = -1,
	LINX_FD_TYPE_UNKNOWN = 0,
	LINX_FD_TYPE_FILE = 1,
	LINX_FD_TYPE_DIRECTORY = 2,
	LINX_FD_TYPE_IPV4_SOCK = 3,
	LINX_FD_TYPE_IPV6_SOCK = 4,
	LINX_FD_TYPE_IPV4_SERVSOCK = 5,
	LINX_FD_TYPE_IPV6_SERVSOCK = 6,
	LINX_FD_TYPE_FIFO = 7,
	LINX_FD_TYPE_UNIX_SOCK = 8,
	LINX_FD_TYPE_EVENT = 9,
	LINX_FD_TYPE_UNSUPPORTED = 10,
	LINX_FD_TYPE_SIGNALFD = 11,
	LINX_FD_TYPE_EVENTPOLL = 12,
	LINX_FD_TYPE_INOTIFY = 13,
	LINX_FD_TYPE_TIMERFD = 14,
	LINX_FD_TYPE_NETLINK = 15,
	LINX_FD_TYPE_FILE_V2 = 16,
	LINX_FD_TYPE_BPF = 17,
	LINX_FD_TYPE_USERFAULTFD = 18,
	LINX_FD_TYPE_IOURING = 19,
	LINX_FD_TYPE_MEMFD = 20,
	LINX_FD_TYPE_PIDFD = 21,
    LINX_FD_TYPE_MAX
} linx_fd_type_t;

#endif /* __LINX_FD_TYPE_H__ */
