#include <stdlib.h>
#include <string.h>
#include "linx_event_classifier.h"

/**
 * 事件类型到事件源的映射表
 * 根据系统调用的功能进行分类
 */
static const struct {
    uint32_t type;
    linx_event_source_t source;
} event_type_source_map[] = {
    /* 文件I/O操作 */
    {LINX_EVENT_TYPE_READ_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_READ_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_WRITE_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_WRITE_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_OPEN_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_OPEN_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_OPENAT_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_OPENAT_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_CLOSE_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_CLOSE_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_PREAD64_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_PREAD64_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_PWRITE64_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_PWRITE64_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_READV_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_READV_X, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_WRITEV_E, LINX_EVENT_SOURCE_FILE_IO},
    {LINX_EVENT_TYPE_WRITEV_X, LINX_EVENT_SOURCE_FILE_IO},
    
    /* 网络操作 */
    {LINX_EVENT_TYPE_SOCKET_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_SOCKET_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_CONNECT_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_CONNECT_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_ACCEPT_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_ACCEPT_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_SENDTO_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_SENDTO_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_RECVFROM_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_RECVFROM_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_SENDMSG_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_SENDMSG_X, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_RECVMSG_E, LINX_EVENT_SOURCE_NETWORK},
    {LINX_EVENT_TYPE_RECVMSG_X, LINX_EVENT_SOURCE_NETWORK},
    
    /* 进程管理 */
    {LINX_EVENT_TYPE_CLONE_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_CLONE_X, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_FORK_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_FORK_X, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_VFORK_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_VFORK_X, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_EXECVE_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_EXECVE_X, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_EXIT_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_EXIT_X, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_WAIT4_E, LINX_EVENT_SOURCE_PROCESS},
    {LINX_EVENT_TYPE_WAIT4_X, LINX_EVENT_SOURCE_PROCESS},
    
    /* 内存管理 */
    {LINX_EVENT_TYPE_MMAP_E, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_MMAP_X, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_MUNMAP_E, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_MUNMAP_X, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_MPROTECT_E, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_MPROTECT_X, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_BRK_E, LINX_EVENT_SOURCE_MEMORY},
    {LINX_EVENT_TYPE_BRK_X, LINX_EVENT_SOURCE_MEMORY},
    
    /* 信号处理 */
    {LINX_EVENT_TYPE_KILL_E, LINX_EVENT_SOURCE_SIGNAL},
    {LINX_EVENT_TYPE_KILL_X, LINX_EVENT_SOURCE_SIGNAL},
    {LINX_EVENT_TYPE_RT_SIGACTION_E, LINX_EVENT_SOURCE_SIGNAL},
    {LINX_EVENT_TYPE_RT_SIGACTION_X, LINX_EVENT_SOURCE_SIGNAL},
    {LINX_EVENT_TYPE_RT_SIGPROCMASK_E, LINX_EVENT_SOURCE_SIGNAL},
    {LINX_EVENT_TYPE_RT_SIGPROCMASK_X, LINX_EVENT_SOURCE_SIGNAL},
    
    /* 进程间通信 */
    {LINX_EVENT_TYPE_PIPE_E, LINX_EVENT_SOURCE_IPC},
    {LINX_EVENT_TYPE_PIPE_X, LINX_EVENT_SOURCE_IPC},
    
    /* 文件系统操作 */
    {LINX_EVENT_TYPE_STAT_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_STAT_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_FSTAT_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_FSTAT_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_LSTAT_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_LSTAT_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_CHMOD_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_CHMOD_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_CHOWN_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_CHOWN_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_MKDIR_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_MKDIR_X, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_RMDIR_E, LINX_EVENT_SOURCE_FILESYSTEM},
    {LINX_EVENT_TYPE_RMDIR_X, LINX_EVENT_SOURCE_FILESYSTEM},
    
    /* 安全相关 */
    {LINX_EVENT_TYPE_SETUID_E, LINX_EVENT_SOURCE_SECURITY},
    {LINX_EVENT_TYPE_SETUID_X, LINX_EVENT_SOURCE_SECURITY},
    {LINX_EVENT_TYPE_SETGID_E, LINX_EVENT_SOURCE_SECURITY},
    {LINX_EVENT_TYPE_SETGID_X, LINX_EVENT_SOURCE_SECURITY},
    {LINX_EVENT_TYPE_PTRACE_E, LINX_EVENT_SOURCE_SECURITY},
    {LINX_EVENT_TYPE_PTRACE_X, LINX_EVENT_SOURCE_SECURITY},
    
    /* 系统信息 */
    {LINX_EVENT_TYPE_UNAME_E, LINX_EVENT_SOURCE_SYSTEM},
    {LINX_EVENT_TYPE_UNAME_X, LINX_EVENT_SOURCE_SYSTEM},
    {LINX_EVENT_TYPE_SYSINFO_E, LINX_EVENT_SOURCE_SYSTEM},
    {LINX_EVENT_TYPE_SYSINFO_X, LINX_EVENT_SOURCE_SYSTEM},
    
    /* 时间相关 */
    {LINX_EVENT_TYPE_GETTIMEOFDAY_E, LINX_EVENT_SOURCE_TIME},
    {LINX_EVENT_TYPE_GETTIMEOFDAY_X, LINX_EVENT_SOURCE_TIME},
    {LINX_EVENT_TYPE_TIME_E, LINX_EVENT_SOURCE_TIME},
    {LINX_EVENT_TYPE_TIME_X, LINX_EVENT_SOURCE_TIME},
};

static const char *event_source_strings[] = {
    "FILE_IO",
    "NETWORK", 
    "PROCESS",
    "MEMORY",
    "SIGNAL",
    "IPC",
    "FILESYSTEM",
    "SECURITY",
    "SYSTEM",
    "TIME",
    "UNKNOWN"
};

static const char *event_direction_strings[] = {
    "ENTER",
    "EXIT"
};

int linx_event_classifier_init(void)
{
    /* 目前不需要特殊的初始化 */
    return 0;
}

void linx_event_classifier_deinit(void)
{
    /* 目前不需要特殊的清理 */
}

linx_event_source_t linx_event_type_to_source(uint32_t event_type)
{
    size_t map_size = sizeof(event_type_source_map) / sizeof(event_type_source_map[0]);
    
    for (size_t i = 0; i < map_size; i++) {
        if (event_type == event_type_source_map[i].type) {
            return event_type_source_map[i].source;
        }
    }
    
    return LINX_EVENT_SOURCE_UNKNOWN;
}

linx_event_direction_t linx_event_type_to_direction(uint32_t event_type)
{
    /* 根据事件类型的奇偶性判断方向
     * 偶数为ENTER (_E)，奇数为EXIT (_X)
     */
    return (event_type % 2 == 0) ? LINX_EVENT_DIRECTION_ENTER : LINX_EVENT_DIRECTION_EXIT;
}

int linx_event_classify(const linx_event_t *event, linx_event_classification_t *classification)
{
    if (!event || !classification) {
        return -1;
    }
    
    classification->type = event->type;
    classification->source = linx_event_type_to_source(event->type);
    classification->direction = linx_event_type_to_direction(event->type);
    
    return 0;
}

const char *linx_event_source_to_string(linx_event_source_t source)
{
    if (source >= LINX_EVENT_SOURCE_MAX) {
        return event_source_strings[LINX_EVENT_SOURCE_UNKNOWN];
    }
    return event_source_strings[source];
}

const char *linx_event_direction_to_string(linx_event_direction_t direction)
{
    if (direction >= LINX_EVENT_DIRECTION_MAX) {
        return "UNKNOWN";
    }
    return event_direction_strings[direction];
}